version: "3"

services:
  manager:
    
    image: nghiack7/manager-app:v2-release
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MNG_PORT}:${MNG_PORT}"
    volumes:
      - ./manage.db:/home/deploy/mng/manage.db
